version: '3.3'
services:
 db:
  image: mysql:5.7
  volumes:
   - db_data:/var/lib/mysql
  restart: always
  environment:
   MYSQL_ROOT_PASSWORD: Dandr@root_MYSQL

 wordpress00:
  depends_on:
   - db
  image: wordpress:latest
  volumes:
   - ./wp00:/var/www/html
  ports:
   - "8000:80"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_PASSWORD: Dandr@root_MYSQL
   WORDPRESS_DB_NAME: wordpress00

 wordpress10:
  depends_on:
   - db
  image: wordpress:latest
  volumes:
   - ./wp10:/var/www/html
  ports:
   - "8010:80"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_PASSWORD: Dandr@root_MYSQL
   WORDPRESS_DB_NAME: wordpress10

 wordpress20:
  depends_on:
   - db
  image: wordpress:latest
  volumes:
   - ./wp20:/var/www/html
  ports:
   - "8020:80"
  restart: always
  environment:
   WORDPRESS_DB_HOST: db:3306
   WORDPRESS_DB_USER: root
   WORDPRESS_DB_PASSWORD: Dandr@root_MYSQL
   WORDPRESS_DB_NAME: wordpress20

 python3:
   restart: always
   build: .
   container_name: 'python3'
   working_dir: '/root/'
   tty: true
   volumes:
    - ./opt:/root/opt

volumes:
  db_data: {}
